### PR TITLE
Low hanging optimizations

### PR DESCRIPTION
**Pull request by szarouski**
Hi, I've made couple of simple optimizations which increase module loading speed. I've run tests and everything is passing just fine. Please review and let me know what you think. Thanks.

### CODE REVIEW

**Comment by jgallen23** [comment]
Can you merge master into your pull request and I'll get it in the next release

**Comment by szarouski** [comment]
@jgallen23, sure I'll do it soon.

**Comment by jgallen23** [comment]
thanks

**Comment by szarouski** [comment]
Question, it was quite easy to merge, but when I run `npm test` I got bunch of errors. I then cloned original `firstandthird/load-grunt-config`, to verify if there are existing issues with tests, and tried `npm test` there, however I'm still getting bunch of errors both on windows and debian. See screen-shot below, is it normal?



After merge I'm getting same number of failing tests, so I dare to assume that my changes are not a reason of these failures.

**Comment by jgallen23** [comment]
I'll look into the failing tests. I merged a bunch of other stuff in today.

**Comment by szarouski** [comment]
Merge is done.

**Pull request merged**
