### PR TITLE
added travis configuration file and badge

### PR DESCRIPTION
**Pull request by jigardafda**
@SolomoN-ua i have added travis config and badge to readme file, could you setup travis account and do the test build. 

this will help everyone in tracking the build failures.

### CODE REVIEW

**Comment by SolomoN-ua** [comment]
Hi @jigardafda, thanks. Good idea, we will try to do this next week.

**Comment by jdat82** [comment]
I don't know if that's possible at all for this project, but it would be even better to make it play tests too.

**Comment by SolomoN-ua** [comment]
@jigardafda, @jdat82 I'm waiting when @jgallen23 will give me access to project travis build
sorry for delay :(

**Comment by jgallen23** [comment]
setting that up now

**Comment by jgallen23** [comment]
all set up: https://travis-ci.org/firstandthird/load-grunt-config

**Comment by SolomoN-ua** [comment]
@jgallen23 Thank you! :)

**Pull request merged**
