### PR TITLE
Update dependencies

### LINKED ISSUE #181: npm audit for lodash@4.17.11
There is a high security vulnerability in `lodash` 4.17.11 that is being used by this package:

```
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.12                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ load-grunt-config [dev]                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ load-grunt-config > lodash                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1065                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

It should be safe to simply update `lodash` to 4.17.14 (perhaps this should be a caret reference to avoid these kinds of manual upgrades going forward? i.e., `^4.17.14`).

### PR DESCRIPTION
**Pull request by rejas**
Fixes #181

### CODE REVIEW

**Comment by circlecube** [comment]
We could use this fix on a project too. Thanks @rejas

**Comment by SolomoN-ua** [comment]
Thanks @rejas will publish new version soon.

**Comment by SolomoN-ua** [comment]
Done: 2.0.1 & 3.0.0-rc3

**Comment by rejas** [comment]
Thx for the quick merge and release!

**Pull request merged**
